// <auto-generated />
namespace wallchat.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addnewFileentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewFileentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201704171205214_add new File entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
