// <auto-generated />
namespace wallchat.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Compareusertonew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Compareusertonew));
        
        string IMigrationMetadata.Id
        {
            get { return "201704151455446_Compare user to new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
