// <auto-generated />
namespace wallchat.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deldeletingdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deldeletingdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201705082034337_del deleting date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
